### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DarkCat09** [DarkCat09/autoytdlp#1]
"Mirrored" from https://git.dc09.ru/DarkCat09/autoytdlp/issues/1#issue-30

### Structure & main script
- [ ] Maybe move all downloaded & generated files into `files/`, id3tagging scripts into `id3/`, and so on
- [ ] Make one script loading (`source id3/main.sh`) these scripts instead of Makefile
- [ ] Make a GUI (in addition to TUI) in PyQt6 or another framework

### Main script
- [ ] More handy TUI
- [ ] Remembering the links list
- [ ] Properly handling different errors
- [ ] Piped/Invidious/yt-dlp
- [ ] Optimization: use wget's/yt-dlp's batch processing

### ID3Tags
- [ ] SearXNG's JSON API instead of parsing HTML
- [ ] Fix Azlyrics encoding
- [ ] Get a list of albums from Azlyrics, filter out EPs if there is anything except them, choose the `[0]`th
- [ ] Do not raise error and exit from the function when unable to parse album, just let the user fill in remaining fields (not all fields, but only that have not been parsed)
- [ ] (?) Implement Genius parsing
- [ ] (???) Use Genius API when Azlyrics is unavailable
